const WA="5491178193961";
const MP="https://www.mercadopago.com.ar/checkout/v1/redirect?pref_id=1413458706-82e09e02-bbea-4ea6-b7ec-237d480df8d6";
const CRM="https://crm-supabase-six.vercel.app/api/lead-intake";
const PROVINCES=["Buenos Aires","CABA","Córdoba","Santa Fe","Mendoza","Tucumán","Entre Ríos","Salta","Chaco","Corrientes","Misiones","Santiago del Estero","San Juan","Jujuy","Río Negro","Neuquén","Formosa","Chubut","San Luis","Catamarca","La Rioja","La Pampa","Santa Cruz","Tierra del Fuego"];
const TRACK=["gclid","gbraid","wbraid","utm_source","utm_medium","utm_campaign","utm_term","utm_content"];
const pos={contact:1,cuit:2,dniStatus:3,residence:4,billing:5,eligible:6,key:7,activity:8,sector:9,province:10,premises:11,identity:12,qualified:12,redirect:12,manual:5,duplicate:12,already:12,paid:12};
const back={cuit:"contact",dniStatus:"cuit",residence:"dniStatus",billing:"dniStatus",key:"eligible",activity:"key",sector:"activity",province:"sector",premises:"province",identity:"premises"};
let stage="contact", warnedEmail="", lead={nombre:"",apellido:"",telefono:"",email:"",website:"",tiene_cuit:"",dni_argentino:"",tiene_precaria:"",sabe_facturacion:"",monto_estimado:"",clave_fiscal:"",actividad_tipo:"",rubro:"",provincia:"",local:"",dni:"",cuit:""};
const funnel=document.getElementById("funnel"), esc=s=>String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;"}[c]));
function tracking(){try{return JSON.parse(localStorage.getItem("ts_tracking")||"{}")}catch{return {}}}
async function send(extra){if(["localhost","127.0.0.1"].includes(location.hostname)||location.protocol==="file:")return {ok:true};const payload={...lead,...extra,...tracking(),origen:"monotributolisto.com",variante:"B",producto:"alta_monotributo",landing_url:location.origin+location.pathname,referrer:document.referrer||null,user_agent:navigator.userAgent,ts:new Date().toISOString()};const r=await fetch(CRM,{method:"POST",headers:{"Content-Type":"text/plain"},body:JSON.stringify(payload)});if(!r.ok)throw Error("save");return r.json().catch(()=>({ok:true}))}
function save(estado,extra={}){send({...extra,estado}).catch(()=>{})}
function validCuit(v){const c=v.replace(/\D/g,"");if(!/^\d{11}$/.test(c))return false;const m=[5,4,3,2,7,6,5,4,3,2];let sum=0;for(let i=0;i<10;i++)sum+=+c[i]*m[i];let d=11-sum%11;if(d===11)d=0;return d!==10&&d===+c[10]}
function distance(a,b){const m=Array.from({length:b.length+1},()=>Array(a.length+1).fill(0));for(let i=0;i<=b.length;i++)m[i][0]=i;for(let j=0;j<=a.length;j++)m[0][j]=j;for(let i=1;i<=b.length;i++)for(let j=1;j<=a.length;j++)m[i][j]=b[i-1]===a[j-1]?m[i-1][j-1]:Math.min(m[i-1][j-1],m[i][j-1],m[i-1][j])+1;return m[b.length][a.length]}
function suggestEmail(email){const p=email.split("@");if(p.length!==2)return null;const ds=["gmail.com","hotmail.com","outlook.com","yahoo.com","yahoo.com.ar","icloud.com","live.com","hotmail.com.ar","outlook.com.ar"];if(ds.includes(p[1].toLowerCase()))return null;const d=ds.find(x=>distance(p[1].toLowerCase(),x)<=2);return d?`${p[0]}@${d}`:null}
function legal(){return `<small class="legal">Al continuar aceptás que Monotributo Listo y el prestador identificado en los <a href="terminos.html">Términos y condiciones</a> te contacten, y declarás haber leído la <a href="privacidad.html">Política de privacidad</a>. No te pediremos la clave fiscal en este formulario. El trámite básico también puede realizarse gratis en ARCA.</small>`}
function q(k,t,p,inside){return `<div class="form-step question"><small>${k}</small><h2>${t}</h2><p>${p}</p>${inside}</div>`}
function result(icon,k,t,p,inside,danger=false){return `<div class="success ${danger?"danger":""}"><div>${icon}</div><small>${k}</small><h2>${t}</h2><p>${p}</p>${inside}</div>`}
function choices(field,arr){return `<div class="choices ${arr.length<=3?"row":""}">${arr.map(([v,l])=>`<button type="button" data-choice="${field}" data-value="${v}" class="${lead[field]===v?"selected":""}">${l}</button>`).join("")}</div>`}
function nav(disabled=false){return `<div class="form-actions">${back[stage]?`<button type="button" class="back" data-back>← Anterior</button>`:""}<button type="button" class="primary" data-next ${disabled?"disabled":""}>Siguiente <span>↗</span></button></div>`}
function error(text){return text?`<div class="error" role="alert">${esc(text)}</div>`:""}
function render(err=""){
 document.getElementById("step-now").textContent=pos[stage];document.getElementById("progress").style.width=`${pos[stage]/12*100}%`;document.getElementById("form-label").textContent=stage==="paid"?"Pago confirmado":stage==="already"?"Tu solicitud":"Empezá tu solicitud";
 if(stage==="contact")funnel.innerHTML=`<form id="contact-form" novalidate><div class="honeypot" aria-hidden="true"><input id="website" tabindex="-1" autocomplete="off"></div>${q("Tus datos","¿Con quién hablamos?","Guardamos este primer paso aunque después no termines el formulario.",`<div class="fields two"><label>Nombre<input id="nombre" autofocus value="${esc(lead.nombre)}" placeholder="Tu nombre"></label><label>Apellido<input id="apellido" value="${esc(lead.apellido)}" placeholder="Tu apellido"></label></div><label>WhatsApp<input id="telefono" inputmode="numeric" maxlength="10" value="${esc(lead.telefono)}" placeholder="11 2345 6789"></label><label>Email<input id="email" type="email" value="${esc(lead.email)}" placeholder="nombre@correo.com"></label>`) }${error(err)}<div class="form-actions"><button class="primary">Empezar mi alta <span>↗</span></button></div>${legal()}</form>`;
 else if(stage==="cuit")funnel.innerHTML=q("Calificación","¿Tenés CUIT o CUIL?","No pasa nada si todavía no lo tenés.",choices("tiene_cuit",[["si","Sí"],["no","No"]])+nav(!lead.tiene_cuit));
 else if(stage==="dniStatus")funnel.innerHTML=q("Calificación","¿Tenés DNI argentino?","Esto define si el alta puede continuar completamente online.",choices("dni_argentino",[["si","Sí"],["no","No"]])+nav(!lead.dni_argentino));
 else if(stage==="residence")funnel.innerHTML=q("Residencia","¿Tenés residencia precaria o permanente en Argentina?","La necesitamos para determinar si podemos gestionar el alta por este medio.",choices("tiene_precaria",[["si","Sí"],["no","No"]])+nav(!lead.tiene_precaria));
 else if(stage==="billing")funnel.innerHTML=q("Ingresos estimados","¿Tenés una idea de cuánto vas a facturar por mes?","Es una estimación; sirve para orientar correctamente tu categoría.",choices("sabe_facturacion",[["si","Sí"],["no","No"]])+(lead.sabe_facturacion==="si"?`<label>Monto estimado por mes<input id="monto_estimado" inputmode="numeric" value="${lead.monto_estimado?`$${Number(lead.monto_estimado).toLocaleString("es-AR")}`:""}" placeholder="$0"></label>`:"")+nav(!lead.sabe_facturacion||(lead.sabe_facturacion==="si"&&!lead.monto_estimado)));
 else if(stage==="eligible")funnel.innerHTML=result("✓","Precalificación completa","¡Muy bien! Podés darte de alta.","Ahora sí, necesitamos los últimos datos para armar tu trámite.",`<button class="primary" data-next>Continuar <span>↗</span></button>`);
 else if(stage==="key")funnel.innerHTML=q("Tu situación","¿Tenés clave fiscal?","No te la vamos a pedir en este formulario.",choices("clave_fiscal",[["si","Sí"],["no","No"],["no_se","No sé"]])+nav(!lead.clave_fiscal));
 else if(stage==="activity")funnel.innerHTML=q("Tu actividad","¿A qué te dedicás?","Elegí la opción que más se acerque a tu caso.",choices("actividad_tipo",[["servicios","Servicios · freelance, delivery, oficios"],["ventas","Venta de productos"],["ambos","Ambos"]])+nav(!lead.actividad_tipo));
 else if(stage==="sector")funnel.innerHTML=q("Tu actividad","Contanos tu rubro.","Con una descripción breve es suficiente.",`<label>Rubro o actividad<input id="rubro" autofocus value="${esc(lead.rubro)}" placeholder="Ej. diseño, delivery, clases particulares…"></label>`+nav(lead.rubro.trim().length<3));
 else if(stage==="province")funnel.innerHTML=q("Tu jurisdicción","¿En qué provincia estás?","La jurisdicción es parte de la inscripción.",`<label>Provincia<select id="provincia"><option value="">Seleccioná</option>${PROVINCES.map(p=>`<option ${lead.provincia===p?"selected":""}>${p}</option>`).join("")}</select></label>`+nav(!lead.provincia));
 else if(stage==="premises")funnel.innerHTML=q("Tu actividad","¿Tenés local comercial?","Este dato puede influir en la categoría.",choices("local",[["no","No tengo"],["si","Sí tengo"]])+nav(!lead.local));
 else if(stage==="identity")funnel.innerHTML=q("Últimos datos","Validemos tu identidad.","Usamos el DNI para evitar trámites o pagos duplicados.",`<label>DNI<input id="dni" autofocus inputmode="numeric" maxlength="8" value="${esc(lead.dni)}" placeholder="30123456"></label><label>CUIT / CUIL <span class="optional">(opcional)</span><input id="cuit" inputmode="numeric" maxlength="11" value="${esc(lead.cuit)}" placeholder="Si no tenés, lo gestionamos nosotros"></label>${error(err)}${nav(!lead.dni)}`);
 else if(stage==="qualified")funnel.innerHTML=result("✓","Solicitud calificada","¡Listo! Tu alta puede iniciarse hoy.","Con tus datos ya tenemos todo lo necesario. Confirmá para coordinar el pago y arrancar el trámite.",`<button class="primary" id="confirm">Confirmar y continuar <span>↗</span></button>${legal()}`);
 else if(stage==="redirect")funnel.innerHTML=result("◷","Datos guardados","Te estamos llevando al pago.","Si la redirección no se abre, podés continuar desde el botón.",`<a class="primary" href="${MP}">Ir a Mercado Pago <span>↗</span></a>`);
 else if(stage==="manual")funnel.innerHTML=result("×","Revisión manual","Por ahora no podemos avanzar online.","Según tus respuestas, tu caso necesita una revisión particular. Te ayudamos igual por WhatsApp.",`<a class="primary" href="https://wa.me/${WA}?text=${encodeURIComponent("Hola, completé el formulario y necesito ayuda con mi alta de Monotributo")}">Hablar por WhatsApp <span>↗</span></a><button class="back standalone-back" id="review-answer">← Revisar mi respuesta</button>`,true);
 else if(stage==="duplicate")funnel.innerHTML=result("!","Trámite detectado","Ya tenés un trámite iniciado.","Encontramos un pago confirmado con este DNI. Escribinos y seguimos tu caso sin generar otro cobro.",`<a class="primary" href="https://wa.me/${WA}?text=${encodeURIComponent("Hola, ya había pagado mi alta de Monotributo y quiero consultar el estado")}">Consultar por WhatsApp <span>↗</span></a>`,true);
 else if(stage==="already")funnel.innerHTML=result("✓","Solicitud guardada","Ya completaste el formulario.","Si todavía no pagaste, continuá desde el mismo enlace. Si es para otra persona, empezá de nuevo.",`<a class="primary" href="${MP}">Ir a Mercado Pago <span>↗</span></a><button class="back standalone-back" id="reset">Completar otra solicitud</button>`);
 else funnel.innerHTML=result("✓","Pago recibido","¡Listo! Recibimos tu pago.","Guardamos la confirmación. En unos segundos te llevamos a WhatsApp para continuar con un asesor.",`<a class="primary whatsapp-button" href="https://wa.me/${WA}?text=${encodeURIComponent("Hola, ya realicé el pago de mi alta de Monotributo. ¿Cómo seguimos?")}">Continuar por WhatsApp <span>↗</span></a><div class="redirect-bar"><i></i></div>`);
 bind();
}
function updateInputs(){["nombre","apellido","telefono","email","website","monto_estimado","rubro","provincia","dni","cuit"].forEach(id=>{const el=document.getElementById(id);if(el)el.addEventListener(id==="provincia"?"change":"input",()=>{let v=el.value;if(["telefono","dni","cuit","monto_estimado"].includes(id))v=v.replace(/\D/g,"");lead[id]=v;const next=document.querySelector("[data-next]");if(next){if(id==="monto_estimado")next.disabled=!lead.monto_estimado;if(id==="rubro")next.disabled=lead.rubro.trim().length<3;if(id==="provincia")next.disabled=!lead.provincia;if(id==="dni")next.disabled=!lead.dni}})})}
function bind(){updateInputs();document.querySelectorAll("[data-choice]").forEach(b=>b.onclick=()=>{lead[b.dataset.choice]=b.dataset.value;render()});document.querySelector("[data-back]")?.addEventListener("click",()=>{stage=stage==="billing"&&lead.dni_argentino==="no"?"residence":back[stage];render()});document.querySelector("[data-next]")?.addEventListener("click",next);document.getElementById("contact-form")?.addEventListener("submit",contact);document.getElementById("confirm")?.addEventListener("click",confirm);document.getElementById("review-answer")?.addEventListener("click",()=>{stage="residence";render()});document.getElementById("reset")?.addEventListener("click",()=>{localStorage.removeItem("ts_completado");stage="contact";render()})}
function contact(e){e.preventDefault();["nombre","apellido","telefono","email","website"].forEach(id=>{const el=document.getElementById(id);lead[id]=el?el.value.trim():lead[id]});const phone=lead.telefono.replace(/\D/g,"");if(lead.website)return;if(lead.nombre.length<2)return render("Ingresá tu nombre.");if(phone.length!==10)return render("El celular debe tener 10 dígitos, sin 0 ni 15. Ejemplo: 11 1234-5678.");if(!/^[^\s@]+@[^\s@]+\.[a-zA-Z]{2,}$/.test(lead.email))return render("Ingresá un email válido.");const s=suggestEmail(lead.email);if(s&&warnedEmail!==lead.email){warnedEmail=lead.email;return render(`¿Quisiste decir ${s}? Corregilo o volvé a continuar si tu email es correcto.`)}lead.telefono=phone;save("paso_1",{telefono:phone});stage="cuit";render()}
async function next(){if(stage==="cuit"){save("progreso_cuit");stage="dniStatus"}else if(stage==="dniStatus"){save("progreso_dni");stage=lead.dni_argentino==="no"?"residence":"billing"}else if(stage==="residence"){if(lead.tiene_precaria==="no"){save("no_apto");stage="manual"}else{save("progreso_residencia");stage="billing"}}else if(stage==="billing"){save("apto");stage="eligible"}else if(stage==="eligible")stage="key";else if(stage==="key"){save("progreso_clave_fiscal");stage="activity"}else if(stage==="activity"){save("progreso_actividad");stage="sector"}else if(stage==="sector"){save("progreso_rubro");stage="province"}else if(stage==="province"){save("progreso_provincia");stage="premises"}else if(stage==="premises"){save("progreso_local");stage="identity"}else if(stage==="identity"){const dni=lead.dni.replace(/\D/g,""),cuit=lead.cuit.replace(/\D/g,"");if(dni.length<7||dni.length>8)return render("Ingresá un DNI válido, sin puntos.");if(cuit&&!validCuit(cuit))return render("Ese CUIT/CUIL no es válido. Si no lo tenés, dejalo vacío.");let duplicate=false;try{duplicate=!!(await send({action:"check_dni",dni})).duplicate}catch{}lead.dni=dni;lead.cuit=cuit;if(duplicate){save("dni_duplicado",{dni,cuit});stage="duplicate"}else{save("calificado",{dni,cuit});stage="qualified"}}render()}
function confirm(){save("completo");try{localStorage.setItem("ts_completado",JSON.stringify({link:MP,ts:new Date().toISOString()}));localStorage.setItem("ts_lead_pago",JSON.stringify({telefono:lead.telefono,nombre:lead.nombre,apellido:lead.apellido,email:lead.email,dni:lead.dni}))}catch{}stage="redirect";render();setTimeout(()=>location.href=MP,1200)}
try{const q=new URLSearchParams(location.search),stored=tracking();let changed=false;TRACK.forEach(k=>{const v=q.get(k);if(v){stored[k]=v;changed=true}});if(changed){stored.captured_at=new Date().toISOString();localStorage.setItem("ts_tracking",JSON.stringify(stored))}if(q.get("pago")==="exitoso"){stage="paid";setTimeout(()=>location.href=`https://wa.me/${WA}?text=${encodeURIComponent("Hola, ya realicé el pago de mi alta de Monotributo. ¿Cómo seguimos?")}`,4000)}else if(JSON.parse(localStorage.getItem("ts_completado")||"null")?.link)stage="already"}catch{}
render();
document.querySelectorAll(".faq-list article button").forEach(btn=>btn.onclick=()=>{const item=btn.closest("article"),was=item.classList.contains("open");document.querySelectorAll(".faq-list article").forEach(x=>{x.classList.remove("open");x.querySelector("b").textContent="+"});if(!was){item.classList.add("open");btn.querySelector("b").textContent="−"}});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting&&e.target.classList.add("visible")),{threshold:.12});document.querySelectorAll(".reveal").forEach(el=>observer.observe(el));
